spring:
  application:
    name: eureka-server
server:
  port: 8761

eureka:
  instance:
    appname: eureka-server
    hostname: localhost
  client:
    register-with-eureka: false #uygulama eureka servera  service olarak kendini kaydetmesin
    fetch-registry: false  # uygulamanın başlangıcta service lerin registerlarını registerını almasın
    service-url:
      default-zone: http://${eureka.instance.hostname}:${server.port}/eureka



